### ISSUE TITLE
Alternatives to core component (Artemis Global Tracker)?

### ISSUE THREAD

**Issue by AndresSepulveda** [jerabaul29/OpenMetBuoy-v2021a#52]
Hi,

 Seems the SparkFun Artemis Global Tracker is out of stock. Do you have alternatives to this component?

https://www.sparkfun.com/products/18712

I wonder if it is being dicontinued or it is just a temporal glitch.

 Regards,

  Andres

**Comment by jerabaul29** [comment]
(but my 2 cents @AndresSepulveda : if you plan a large deployment, try to start with the procurement of the parts at least 6 months in advance if possible, as things are a bit chaotic with the ongoing chips shortage; I think that contacting SF well in time, they will usually be able to set up a custom run if necessary - at least this is what I experienced :) ).

**Comment by jerabaul29** [comment]
That sounds excellent :) . And of course, if you have any more questions, open an issue here on the repo :) . If you want we can also have a Zoom chat some day - maybe for example after you have had a look at the repo contents, so that we can discuss any question / uncertainty you may have, future developments, etc? :) ).

Btw, depending on your timing, @TryggviLab at Labmaker is working (still WIP, you should check with him, and I think they at Labmaker are currently still building / evaluating a prototype to decide if they want to go full scale with the production) on either / both i) providing a "master PCB" that can be used to mount all components to make assembly easier, ii) producing commercially the open source design. So that may be an alternative way to procurement. I will anyways update the Readme when there is anything "firm" on this side :) .

**Comment by AndresSepulveda** [comment]
Great, thanks. Let me clear a few other deadlines and I will contact you for a Zoom chat.

**Comment by jerabaul29** [comment]
A few are back in stock @AndresSepulveda , 4 as of just now, crossing fingers for more soon :) https://www.sparkfun.com/products/18712 .

**Comment by jerabaul29** [comment]
Already sold out again...

**Comment by brhoff720** [comment]
Hi JR and all,

We're working to get more available.  We moved these from SparkX to SparkFun to try to ensure a constant stock level.  However, global supply chain challenges have hindered our efforts.  This is on our radar to get back in stock.

**Comment by jerabaul29** [comment]
Thanks @brhoff720 for the confirmation that you are trying to re-establish some stocks :) .

@AndresSepulveda in the meantime, looks like while SF is sold out, Mouser does have a couple in stock: https://no.mouser.com/ProductDetail/SparkFun/WRL-18712?qs=Rp5uXu7WBW%2FvtVY5LVjy9A%3D%3D .

**Comment by jerabaul29** [comment]
28 AGTs at SF website now, crossing fingers they keep producing do that stocks hold :) . Btw @AndresSepulveda have you been able to build / test the OMB? :) Let me know if there is anything I can do to help :) .

**Comment by jerabaul29** [comment]
(we have deployed nearly 80 in the last 5 months with great success, so the design is definitely good :) ).

**Comment by brhoff720** [comment]
I thought I pinged this thread as they came back in stock.  And yes, we are trying to keep this in stock more consistently.  If you are needing more than you see available, ping me and I will see what can be done to push to front of production queue.

**Comment by AndresSepulveda** [comment]
Not yet, dealing with other issues now, but I do keep it in mind.
-------- Mensaje original --------De: JR ***@***.***> Fecha: 19/8/2022  16:28  (GMT-04:00) A: jerabaul29/OpenMetBuoy-v2021a ***@***.***> CC: Andres Sepulveda ***@***.***>, Mention ***@***.***> Asunto: Re: [jerabaul29/OpenMetBuoy-v2021a] Alternatives to core component (Artemis Global Tracker)? (Issue #52) 
28 AGTs at SF website now, crossing fingers they keep producing do that stocks hold :) . Btw @AndresSepulveda have you been able to build / test the OMB? :) Let me know if there is anything I can do to help :) .
